CREATE TABLE tb_fianca (
    id SERIAL PRIMARY KEY,  -- Substitui AUTOINCREMENT por SERIAL
    uuid TEXT NOT NULL UNIQUE,
    numero_cotacao INTEGER UNIQUE,
    data_hora_cotacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Substitui DATETIME por TIMESTAMP
    codigo_mediador TEXT,
    nome_mediador TEXT,
    email_mediador TEXT,
    telefone_mediador TEXT,
    nome_locatario TEXT,
    cpf_locatario TEXT,
    email_locatario TEXT,
    telefone_locatario TEXT,
    cep_locatario TEXT,
    logradouro_locatario TEXT,
    numero_logradouro_locatario TEXT,
    complemento_logradouro_locatario TEXT,
    cidade_locatario TEXT,
    estado_locatario TEXT,
    score DECIMAL(10, 2), -- Substitui REAL por DECIMAL para maior precisão
    pendencia_financeira DECIMAL(15, 2), -- Substitui REAL por DECIMAL
    nome_locador TEXT,
    cpf_locador TEXT,
    email_locador TEXT,
    telefone_locador TEXT,
    cep_locador TEXT,
    logradouro_locador TEXT,
    numero_logradouro_locador TEXT,
    complemento_logradouro_locador TEXT,
    cidade_locador TEXT,
    estado_locador TEXT,
    tipo_seguro TEXT,
    apolice_anterior INTEGER,
    tipo_locacao TEXT,
    cep_risco TEXT,
    logradouro_risco TEXT,
    numero_logradouro_risco INTEGER,
    complemento_risco TEXT,
    cidade_risco TEXT,
    estado_risco TEXT,
    data_inicio_vigencia DATE,
    data_fim_vigencia DATE,
    periodo INTEGER,
    is_aluguel DECIMAL(15, 2), -- Substitui REAL por DECIMAL
    is_iptu DECIMAL(15, 2),
    is_condominio DECIMAL(15, 2),
    is_agua DECIMAL(15, 2),
    is_energia_eletrica DECIMAL(15, 2),
    is_gas DECIMAL(15, 2),
    is_danos_imovel DECIMAL(15, 2),
    is_pintura_interna DECIMAL(15, 2),
    is_pintura_externa DECIMAL(15, 2),
    is_multa_recisoria DECIMAL(15, 2),
    numero_apolice INTEGER,
    data_hora_emissao TIMESTAMP, -- Substitui DATETIME por TIMESTAMP
    pacote TEXT,
    tipo_pagamento TEXT,
    quantidade_parcelas INTEGER,
    juros_pagamento TEXT,
    taxa_juros_pagamento DECIMAL(5, 3), -- Substitui REAL por DECIMAL
    premio_total DECIMAL(15, 2),
    comissao DECIMAL(15, 2),
    desconto_cap DECIMAL(15, 2),
    iof DECIMAL(15, 2),
    lmg_aluguel DECIMAL(15, 2),
    lmg_iptu DECIMAL(15, 2),
    lmg_condominio DECIMAL(15, 2),
    lmg_agua DECIMAL(15, 2),
    lmg_energia_eletrica DECIMAL(15, 2),
    lmg_gas DECIMAL(15, 2),
    lmg_danos_imovel DECIMAL(15, 2),
    lmg_pintura_interna DECIMAL(15, 2),
    lmg_pintura_externa DECIMAL(15, 2),
    lmg_multa_recisoria DECIMAL(15, 2),
    premio_aluguel DECIMAL(15, 2),
    premio_iptu DECIMAL(15, 2),
    premio_condominio DECIMAL(15, 2),
    premio_agua DECIMAL(15, 2),
    premio_energia_eletrica DECIMAL(15, 2),
    premio_gas DECIMAL(15, 2),
    premio_danos_imovel DECIMAL(15, 2),
    premio_pintura_interna DECIMAL(15, 2),
    premio_pintura_externa DECIMAL(15, 2),
    premio_multa_recisoria DECIMAL(15, 2),
    premio_total_liquido DECIMAL(15, 2),
    status TEXT NOT NULL DEFAULT 'Aguardando processamento da cotacao'
);
